### ISSUE TITLE
OCPNsenc contains faulty RPATH to /home/dsr

### ISSUE THREAD

**Issue by dominig** [bdbcat/s63_pi#13]
When I try to create my package for s63 plugin with the OCPNsenc binary blob provided with 4.2, I get the following error during the installation phase in the chroot :
   ERROR: RPATH "/home/dsr/Projects/wxWidgets-3.0.2/wxWidgets-3.0.2/build_console/lib

I found the faulty RPATH is present in the header on the 64 bit version only (but I only checked for Linux)

>  chrpath -l buildlinux64/OCPNsenc/OCPNsenc | egrep 'RPATH|RUNPATH'
>     buildlinux64/OCPNsenc/OCPNsenc.ori: RPATH=/home/dsr/Projects/wxWidgets-3.0.2/wxWidgets-3.0.2/build_console/lib

Workaround:

I used the command chrpath to remove the RPATH. It build but I do not know if it will work (I have no s-63 chat to test)

>  chrpath -d buildlinux64/OCPNsenc/OCPNsenc

**Comment by leamas** [comment]
Current binaries does not contain any rpath,so I guess this issue could be closed (?)

**Comment by dominig** [comment]
Corrected with V 2 of the plugin.
