### ISSUE TITLE
Licensing

### ISSUE THREAD

**Issue by leamas** [bdbcat/s63_pi#20]
I cannot find a clear answer to the question how this plugin is licensed. 

The file data/license.txt is  has the local modification at top saying 

    This program is distributed under the terms of the GPL v2.

However, looking at the code it seems to be mostly GPL-2+ with some parts using other licenses (Expat, SGI 1.1 B,  MIT). 

I'd suggest that the first line in license.txt (which implies GPL-2 as opposed to GPL-2+) is removed and that README is augmented with something like

    2 Licensing
    This work is distributed under the GPL license version 2 or, at your option, any later version. See
    the file data/license.txt for more.

    Some parts are distributed using other licenses as stated in the source files.

**Comment by filochard** [comment]
Hi 
We maintain rpms of opencpn and its plugins for Mageia
Mageia provides only opensource program in its core repository
But we may provide programs that are not totally opensource in a special repository (non-free) if the pre-built binaries are distributable
There is no clear license for  the OCPNsenc binary !!! so we can't provide this necessary plugin

A contrario, it's clearly allowed for oesenc-plugin to distribute it with its closed source part

Could you please clarify this in the README file  the same way as it is for oesenc-plugin, unless we can't provide the s63-plugin

Thanks

**Comment by filochard** [comment]
see also
https://github.com/bdbcat/oernc_pi/issues/5

**Comment by bdbcat** [comment]
Done.

**Comment by filochard** [comment]
Whaw !
Thanks for a so quick answer and solution
Congratulations

**Comment by filochard** [comment]
For my part of this issue I think you may close this issue

**Comment by leamas** [comment]
So, let's close
