### ISSUE TITLE
Rendering of Obstruction Boundaries

### ISSUE THREAD

**Issue by grhitch** [bdbcat/s63_pi#22]
Hi Dave,
 am using S63 charts from the Australian Hydrographic Service. They were working fine with plugin version 1.14, but have some rendering problems under 1.16.

This problem was referred to on the Cruisers Forum [(https://www.cruisersforum.com/forums/f134/opencpn-version-5-2-0-released-237051-7.html#post3203869).]

When  an obstruction adjoins a land area the enclosing line does not render properly. The screenshot shows this, but also a case where not adjacent to a land area and the rendering is fine. The examples shown in the screenshot are OBSTRN CATOBS 6, but other CATOBS also exhibit this behaviour.

![image](https://user-images.githubusercontent.com/3023194/97056999-05d59480-15d6-11eb-9c4e-b484f6c736c5.png)

I have tried the IHO S57 test data set and there is no problem. I have also tried the sample data set from Australian Hydro (also S57) and again, no problem.

The tests above and The title for commit "Update SENC format to 126, Improved AREA Feature boundary rendering." [https://github.com/bdbcat/s63_pi/commit/255098765fbc3e3dcba2df455443664f000f96a5] suggests that the problem might be there or thereabouts.

I have checked with aboon (the Cruisers Forum post referred to above) and his setup is: Windows 10 Pro (V1909) 64-bit, OCPN V5.2.0 and S63 pi V1.16.725.
I am happy to do any other testing that might help to narrow down the problem.

My setup (2 machines with S63 charts licensed)
Machine 1:
Architecture: AMD64
Ubuntu 20.04.1 LTS
Gnome Version 3.36.3
Windowing System Wayland
OpenCPN Version 5.2.4 (5.2.4.6-0~focal1) - Installed from http://ppa.launchpad.net/bdbcat/opencpn/ubuntu
Working plugin: S63 Plugin 1.14.1626 - Compiled from the orig source (opencpn-plugin-s63_1.14.1626.orig.tar.bz2) downloaded from the OpenCPN PPA
Plugin with issue: S63 Plugin 1.16.725 installed from the plugin catalogue after removing the deb.
The only other plugin active is WMM 1.1.

Machine 2:
Architecture: AMD64
Ubuntu 20.04.1 LTS
Gnome Version 3.36.3
Windowing System X11 also tried Wayland
OpenCPN Version 5.2.4.0-0~bionic1 - Installed from http://ppa.launchpad.net/opencpn/opencpn/ubuntu (the reason that it is Bionic is another story that I will take up elsewhere).
S63 Plugin 1.16.725 installed from the plugin catalogue after removing the deb.

Best Regards
Greg

**Comment by grhitch** [comment]
A bit of additonal information.
Apparently Australian oesENC charts don't have the problem. 
New Zealand S63 charts do have a problem. See for example the image below of Stewart Island wityh a line down the middle.
![image](https://user-images.githubusercontent.com/3023194/97065768-a25e5d80-15fb-11eb-9c9c-b7cff8d50223.png)
Regards
Greg

**Comment by bdbcat** [comment]
Should be corrected by s63_pi Version 1.17.1, available in master catalog now.
Good Luck
Dave

**Comment by grhitch** [comment]
Fantastic!
Thanks for your help on this and all of your efforts for this project. 
It now renders perfectly on both Linux and Windows.
Greg
