### ISSUE TITLE
OCPNsenc needed for ARM processor

### ISSUE THREAD

**Issue by jongough** [bdbcat/s63_pi#9]
Hi, I have just compiled OCPN for an ARM processor machine and run it successfully. I would now like to run the S63 plugin on the same machine. I have compiled the S63 plugin, but the OCPNsenc is a pre-compiled binary and does not appear to be available yet for the ARM processor. Can you generate one so that we can support a bigger range of hardware?

Jon

**Comment by leamas** [comment]
Now, here is  a armhf binary, so I guess this issue could e closed (?)
